name: Configuration Distribution
type: module
description: Framework for managing configuration updates from distributions.
core: 8.x
package: Config
dependencies:
  - config_filter:config_filter
  - config_split:config_split
